const builtin = @import("builtin");
const std = @import("std");

const c = @cImport({
    @cInclude("stddef.h");
    @cInclude("webview.h");
});

pub fn main() !void {
    const w = c.webview_create(if (builtin.mode == .Debug) 1 else 0, null);
    defer _ = c.webview_destroy(w);

    _ = c.webview_set_title(w, "Native App");
    _ = c.webview_set_size(w, 1024, 768, c.WEBVIEW_HINT_NONE);

    // Embed the single-file HTML generated by the UI build
    const config = @import("config");
    const html = config.index_html ++ "\x00";
    _ = c.webview_set_html(w, html);
    _ = c.webview_run(w);
}
